import os
import sys
import json
import re
import time
import sqlite3

# Adjust path to import modules correctly
project_root = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..'))
if project_root not in sys.path:
    sys.path.insert(0, project_root)

# Import necessary components for hardcoded rule testing
from Systems_Engineering_Chatbot.src.hard_rules import detect_morphism_graph_trigger, generate_hardcoded_morphism_graph_response

def run_smoke_test_hardcoded_graph(prompt: str):
    print(f"\n--- Running Smoke Test for Hardcoded Isomorphism Graph ---")
    print(f"Prompt: {prompt}")

    try:
        # Check if the prompt triggers the hardcoded rule
        if detect_morphism_graph_trigger(prompt):
            print("[TEST] Hardcoded graph trigger detected.")
            
            # Generate the hardcoded SVG content
            start = time.time()
            svg_content = generate_hardcoded_morphism_graph_response()
            print(f"[TEST] Hardcoded SVG content generated in {time.time()-start:.2f}s ({len(svg_content)} chars)")

            # Save the SVG to an HTML file for easy viewing
            output_html_path = "hardcoded_isomorphism_graph_output.html"
            with open(output_html_path, "w") as f:
                f.write("<!DOCTYPE html>\n")
                f.write("<html>\n")
                f.write("<head>\n")
                f.write("<title>Hardcoded Isomorphism Graph</title>\n")
                f.write("<style>\n")
                f.write("  body { font-family: sans-serif; margin: 20px; }\n")
                f.write("  svg { border: 1px solid #ccc; display: block; margin-top: 20px; }\n")
                f.write("  pre { background-color: #f0f0f0; padding: 10px; border-radius: 5px; overflow-x: auto; }\n")
                f.write("</style>\n")
                f.write("</head>\n")
                f.write("<body>\n")
                f.write("<h1>Hardcoded Isomorphism Graph Visualization</h1>\n")
                f.write("<p>Below is the SVG generated by the hardcoded routine.</p>\n")
                f.write(svg_content)
                f.write("<h2>Raw SVG Content</h2>\n")
                f.write(f"<pre>{escape_html(svg_content)}</pre>\n")
                f.write("</body>\n")
                f.write("</html>\n")
            
            print(f"[TEST] Visualization saved to {os.path.abspath(output_html_path)}")

            # Basic assertion for smoke test
            assert len(svg_content) > 1000 # SVG should not be empty or too short
            assert "<svg" in svg_content
            assert "</svg>" in svg_content
            assert "Mechanical Spring-Mass-Damper" in svg_content
            assert "Electrical RLC Circuit" in svg_content
            assert "Force and voltage are both first-order effort-type inputs" in svg_content # Check for a justification

            print("\n--- Smoke Test Passed Successfully! ---")
            print(f"To view the graph, open {output_html_path} in your web browser.")

        else:
            print("[TEST] Prompt did NOT trigger the hardcoded graph rule. No visualization generated.")
            print("Please use a prompt like 'create a visual graph' to trigger the rule.")

    except Exception as e:
        print(f"\n--- Smoke Test FAILED: {e} ---")
        import traceback
        traceback.print_exc()

def escape_html(text):
    """Escape HTML characters for display in a <pre> tag."""
    return text.replace("&", "&").replace("<", "<").replace(">", ">").replace('"', """).replace("'", "&#039;")


if __name__ == "__main__":
    # Test prompt that should trigger the hardcoded graph rule
    test_prompt = "create a visual graph of the isomorphisms" 
    run_smoke_test_hardcoded_graph(test_prompt)
